theme: osuny
_merge: deep
params:
  plausible: www.gaite-lyrique.net
  additional_csp: cdn.matomo.cloud gaitelyrique.matomo.cloud 'unsafe-inline'
  debug:
    productionUrl: https://www.gaite-lyrique.net
  summary:
    position: hero
  search:
    active: true
    positions:
      - primary
      - secondary
  home:
    head:
      title: site
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-footer.svg'
  i18n:
    positions:
      - primary
  blocks:
    ignored:
      - block-class-in-hero
      - block-class-in-sidebar
  components:
    lightbox:
      disabled: false
      in_hero:
        disabled: true
  events:
    index:
      archives: false
      sticky_dates: false
      per_page: 15
      options:
        place: true
      highlight_exhibitions:
        future:
          options:
            image: true
    single:
      time_slots:
        date_format: ":date_full"
    share_links:
      enabled: false
    list:
      with_more: true
  exhibitions:
    share_links:
      enabled: false
    single:
      summary:
        position: content
    list:
      with_more: true
  organizations:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
      options:
        subtitle: false
    single:
      options:
        published_at: false
        reading_time: false
        updated_at: false
        authors: false
    share_links:
      enabled: false
  jobs:
    single:
      options:
        reading_time: false
  image_sizes:
    _default:
      pagefind: "555"
    blocks:
      chapter:
        desktop:  1483
      gallery:
        grid:
          desktop:  864
      links:
        desktop: 894
    sections:
      agenda:
        hero_single:
          mobile:   400
          tablet:   800
          desktop:  894
      events:
        children_in_agenda:
          mobile: 302
          tablet:  400
          desktop:  575
        layouts:
          agenda:
            mobile: 302
            tablet:  400
            desktop: 575
          grid:
            mobile:  360
            tablet:  360
            desktop:  864
          list:
            mobile: 327
            tablet:  575
            desktop: 575
      pages:
        item:
          desktop:  864
      posts:
        item:
          desktop:  894
      home:
        hero:
          mobile:  480
          tablet:   1200
          desktop:  1792
