theme: osuny
_merge: deep
params:
  plausible: gaite-lyrique.net
  debug:
    productionUrl: https://www.gaitelyrique.osuny.site
  summary:
    position: hero
  search:
    active: true
    positions:
      - primary
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-footer.svg'
  blocks:
    ignored:
      - block-class-in-hero
      - block-class-in-sidebar
  events:
    index:
      archives: false
      sticky_dates: false
    single:
      time_slots:
        date_format: ":date_full"
    share_links:
      enabled: false
  exhibitions:
    share_links:
      enabled: false
    single:
      summary:
        position: content
  organizations:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
      options:
        subtitle: false
  image_sizes:
    _default:
      pagefind: "555"
    blocks:
      chapter:
        desktop:  1483
      events:
        agenda:
          mobile: 302
        grid:
          desktop:  864
      gallery:
        grid:
          desktop:  864
    sections:
      agenda:
        hero_single:
          mobile:   400
          tablet:   800
          desktop:  512
      pages:
        item:
          desktop:  864
      posts:
        item:
          desktop:  864
      home:
        hero:
          tablet:   1200
          desktop:  1792
